sonar.projectKey=anirbanbasu_odir
sonar.organization=anirbanbasu


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=odir
sonar.projectVersion=0.1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# Sonar duplications are sometimes false positives, so we ignore them for now.
sonar.cpd.exclusions=src/signal_handler.rs,src/downloader/hf_downloader.rs,src/downloader/ollama_downloader.rs
