name: Publish release tags to crates.io

permissions:
    contents: read

on:
    release:
        types:
            - published

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        if: ${{ !github.event.release.prerelease && !github.event.release.draft }}
        runs-on: ubuntu-latest

        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
              with:
                  egress-policy: audit

            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  ref: ${{ github.event.release.tag_name }}

            - name: Publish to crates.io
              run: cargo publish --locked
              env:
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
