name: SonarQube Scan
permissions:
    contents: read
on:
    push:
        branches:
            - master
    pull_request:
        types: [opened, synchronize, reopened]
jobs:
    sonarqube:
        name: SonarQube
        runs-on: ubuntu-latest
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
              with:
                  egress-policy: audit
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
